### ISSUE TITLE
Use in Android Studio

### ISSUE THREAD

**Issue by isOsman** [pietronaccari/Instagram4Android#1]
Hello,can I use this proj in android studio?

**Comment by pietronaccari** [comment]
Ciao, puoi usarlo su Android Studio, basta inserirlo nel file Build.gradle nella sezione Dipendenze

implementation` "com.github.pietronaccari: Instagram4Android: 0.1"

Dovrebbe funzionare e dovresti quindi essere in grado di utilizzare tutte le classi rese disponibili dalla libreria.

Ad essere sinceri, ti dico che non ho scritto questa libreria, ma l'ho biforcuta, per l'uso in un'app personale e l'autore non la rende più disponibile sul suo repository.
